### ISSUE TITLE
Missing instance types on "Host Inference Storage Volumes"

### ISSUE THREAD

**Issue by athewsey** [awsdocs/amazon-sagemaker-developer-guide#80]
`g4dn` and `inf1` instance families (available for inference per the [pricing doc](https://aws.amazon.com/sagemaker/pricing/)) seem to be missing from `doc_source/host-instance-storage.md`.

Please update with the storage capacities for these instance types.

**Comment by tmadl** [comment]
Unfortunately storage capacities are still missing for the instance types mentioned above

Please update with the storage capacities for `g4dn` and `inf1`

**Comment by ngluna** [comment]
Release notes were updated: https://aws.amazon.com/releasenotes/host-instance-storage-volumes-table/ . Note:  The table is intended to be a list of EBS storage volumes we attach on those instances. We don’t attach an EBS volume because it has a local SSD for for g4dn. {Hence, page does not have g4dn}.
